---
- name: Fetch configurations from NetBox and push to GitHub
  hosts: localhost
  gather_facts: no
  vars:
    output_dir: "/home/user1/netbox_data"
    git_repo_path: "/home/user1/netbox_fetch_push/"

  tasks:
    - name: Ensure output directory exists
      file:
        path: "{{ output_dir }}"
        state: directory

    - name: Ensure the git repository directory exists
      file:
        path: "{{ git_repo_path }}"
        state: directory

    - name: Clone the repository if not present
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_path }}"
        version: main
        accept_hostkey: true

    - name: Fetch sites from NetBox
      uri:
        url: "{{ netbox_api_url }}dcim/sites/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
        validate_certs: no  # Set to 'yes' for production
      register: netbox_sites
      failed_when: devices_response.status != 200

    - name: Fetch devices from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
        validate_certs: no  # Set to 'yes' for production
      register: devices_response
      failed_when: devices_response.status != 200

    - name: Fetch racks from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/racks/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
        validate_certs: no  # Set to 'yes' for production
      register: racks_response
      failed_when: racks_response.status != 200

    - name: Save configurations to JSON file
      copy:
        content: |
          {
            "devices": {{ devices_response.content | to_nice_json }},
            "sites": {{ sites_response.content | to_nice_json }},
            "racks": {{ racks_response.content | to_nice_json }}
          }
        dest: "{{ output_dir }}"
        mode: '0644'
      register: json_save_result
      failed_when: json_save_result is not defined
    
    - name: Configure Git user
      command:
        cmd: git config --global user.name {{ git_username }}
        chdir: "{{ git_repo_path }}"
      
    - name: Configure Git email
      command:
        cmd: git config --global user.email {{ git_useremail }}
        chdir: "{{ git_repo_path }}"

    - name: Copy JSON file to repository directory
      copy:
        src: "{{ output_dir }}"
        dest: "{{ git_repo_path }}"
      register: copy_json_result

    - name: Add new files to git
      command:
        cmd: git add .
        chdir: "{{ git_repo_path }}"

    - name: Commit changes to git
      command:
        cmd: git commit -m "Add NetBox data" --allow-empty
        chdir: "{{ git_repo_path }}"
      ignore_errors: yes

    - name: Push changes to GitHub
      command:
        cmd: git push
        chdir: "{{ git_repo_path }}"
      ignore_errors: yes
